# Generated by Django 5.2.6 on 2025-09-30 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_file', models.FileField(upload_to='uploads')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmailResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.TextField()),
                ('subject', models.TextField()),
                ('summary', models.JSONField()),
                ('email_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='summarizer.emailsummary')),
            ],
        ),
    ]
